import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { NotificationProvider } from '@/components/ui/notification-provider';
import { Toaster } from '@/components/ui/toast';
import { AuthProvider } from '@/context/auth-context';

const inter = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <AuthProvider>
          {children}
          <NotificationProvider />
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
